GET http://localhost:8000/inventory/item/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNzQ3OTk4NTA2fQ.9FnUxxmH2e9quRLc21IVnOydgVPwDIDRIDeee_pHYSM